name: Build Python package

on:
  push:
  workflow_call:

jobs:
  build-host:
    runs-on: ubuntu-latest
    container:
      image: python:latest
    defaults:
      run:
        working-directory: ./host
    steps:

    - uses: actions/checkout@v3

    - name: Install build dependencies
      run: pip install flit build

    - run: python -m build

    - name: Upload artifacts to github
      uses: actions/upload-artifact@v3
      with:
        name: riotee_gateway_host
        path: host/dist/